### PR TITLE
QModuleMixin: Make activation support optimizer

### PR DESCRIPTION
**Pull request by shuokay**
This is a quick draft for #144 intended to facilitate discussion, would you happen to have any suggestions? @dacorvo

### CODE REVIEW

**Comment by dacorvo** [comment]
I think optimizers are not adapted to the quantization of activations because the overhead is too high.
I have an upcoming pull-request that better illustrates the differences between quantized weights and activations.

**Comment by shuokay** [comment]
@dacorvo Do you mean the overhead in dynamic quantization? In static quantization, I think there is no additional overhead for quantized inference, as shown in the simplified example below:
```
s_o  * output_int8 = s_w * weight_int8 * s_i * input_int8
=> output_int8 = s_w * s_i / s_o * (weight_int8 * input_int8)
```
We can evaluate `s_w * s_i / s_o` offline, so I think there is no additional overhead for quantized inference at runtime compared to weight only quantization.

**Comment by dacorvo** [comment]
> @dacorvo Do you mean the overhead in dynamic quantization? 

There is no static quantization for activations, only dynamic quantization, because the output of most operations involving quantized tensors will not be expressed with the same bitwidth as the source tensors (int8 * int8 -> int32), and you need to dynamically quantize the outputs.

**Comment by dacorvo** [comment]
I think you are talking about something else, which is the calibration of the activations.

**Pull request closed without merging**
