### PR TITLE
Add final benchmarks on A100

### PR DESCRIPTION
**Pull request by younesbelkada**
Some perplexity numbers were still based on the old script.

### CODE REVIEW

**Comment by younesbelkada** [comment]
cc @dacorvo

**Comment by younesbelkada** [comment]
Ah yes ! Done !

**Review by dacorvo — DISMISSED** [review]
Super nice, love the gemma numbers, thanks !

**Comment by younesbelkada** [comment]
Done !

**Review by dacorvo — APPROVED** [review]

**Pull request merged**
