### PR TITLE
[core] WIP: 2-bit/4-bit MM kernels

### PR DESCRIPTION
**Pull request by alejandroarmas**
This is a work in progress that addresses #65

### Motivation behind this feature  
To my understanding, there were two recent pull requests. One dealt with quantization and adding new types `quanto.int2` and `quanto.int4`, which was added in #68. The other PR involved in #70 and involved packing multiple weights of precision int4/int2 into a single int8 number.

Therefore, to do anything useful as far as ML goes we need custom matrix multiplication kernels for these packed data types.

### Assumptions

1. We can create custom PyTorch operations in the `quanto` namespace by changing  https://github.com/huggingface/quanto/blob/3bddd0a2c0a34b8294b3825e0b7e517a73aa77f5/quanto/library/ops.py
2. Dynamic Dispatch is performed here https://github.com/huggingface/quanto/blob/3bddd0a2c0a34b8294b3825e0b7e517a73aa77f5/quanto/library/ops.py#L46 is so that we can check to see if the optimized kernel exists, otherwise we default to python implementation
4. In order to compile, create shared library and load C++ extensions during runtime, we must change the https://github.com/huggingface/quanto/blob/3bddd0a2c0a34b8294b3825e0b7e517a73aa77f5/quanto/library/ext/cpp/__init__.py
5. We can define our kernel's source code in the `quanto/library/ext/cpp/` folder
6. In our kernel, we might use `TORCH_CHECK` to dispatch into either 2-bit or 4-bit variants of our MM algorithm  
7. I only have an M1 chip, so I can implement only the subset of kernels that involve the CPU or MPS
8. MPS does not support packed types, so I need to get creative with bit manipulation and/or copy data into a different data structure 

### Requirements

- [ ] To support all devices, we use PyTorch's core library with custom default MM operations for python environment 
- [ ] Extend Torch with highly optimized MM operations for packed data in C++, then creating bindings for the python environment for a combination of the 2/4-bit packed types and different hardware accelerator devices (CPU, GPU, etc):
	- [ ] Use PyTorch's `cpp_extension` utility to compile, create shared library and load C++ extensions during runtime
	- [ ] Create Python bindings for interface to custom kernels:
		- Changing `quanto/library/ext/cpp/pybind_module.cpp`

### CODE REVIEW

**Comment by alejandroarmas** [comment]
Yay this is great to hear! I'm excited to contribute to thea MPS MM kernel for packed 2/4-bit types. 

image
I went ahead and copied @younesbelkada's CPP kernels, but with the unpack MPS kernel instead. Here is a print statements demonstrating this MPS implementation. Just to give you a heads up, I am forking from his commit in 92da7ef133b8a3b5f99d75b66a49c47106b39d5a. Let me know if you prefer if I squash commits or start a fresh branch and/or PR.  

Also, I see that you developed https://github.com/huggingface/quanto/blob/main/quanto/library/ext/mps/unpack.mm#L8. Do you have any advice on tooling to assist with the debugging and profiling MPS kernels? I'm running VS Code and I generally use CLI tools, however I'm open to any of your suggestions.

**Comment by alejandroarmas** [comment]
Oh I am now seeing a benchmark script. Thank you for having this! I've gone ahead used it, so I am noticing a ~3x speedup switching from the torch provided CPU and MPS provided matrix operations.   

```
udqmm_4bit[cpu]: python = 3.201 ms, ext = 3.166 ms, ratio = 1.0x
udqmm_4bit[mps]: python = 1.185 ms, ext = 1.611 ms, ratio = 0.7x
```

Also, could you clarify the performance benchmarks for a PR that I should aim for? I'm going off an assumption that anything above a 3x speedup is a win, but I'm probably wrong.

**Comment by alejandroarmas** [comment]
Thank you again for taking the time for all my questions. It really helps me with understanding the problem correctly. I went ahead and wrote what you expect from the solution and some more assumptions I'm making.

#### Requirements

So just that I'm clear if I'm understanding you. In the context of the MPS kernel, I'm imagining that:
1. We unpack the 8-bit values into 2 4-bit values
2. each 4-bit value represents a quantized representation (i.e. lower-precision representation)
3. we use the individual packed values (4-bit values) as we compute matrix multiplication
4. This is done in parallel using the Metal threadgroups 

 
#### Assumptions 

Let me start with my understanding of quantization. My understanding of the CPP source for quantization https://github.com/huggingface/quanto/blob/main/quanto/library/ext/cpp/quantize.cpp#L11 is that it quantizes 16-bit/32-bit floats into 4-bit chars. However, 2-bit quantization is not supported yet?   
I want to run an example by you because I feel that I'm not grasping this well. There is also a scale-axis function I don't get.

##### Quantization Example

Suppose we had a tensor with the following data and wanted to quantize each value to 4-bit precison:
```python
vec = [1.2, -0.5, -4.3, 1.2, -3.1, 0.8, 2.4, 5.4]
```
We extract the max absolute value inside the tensor
```python
abs_max = max(abs(vec)) # 5.4
```
Since we have 4-bit has a range of `[-8, 8]` (i.e. 1 sign bit + rest of bits represent $2^3$ whole numbers). We can use that information to get the scaling factor, we divide 8 by 5.4 and obtain `scaling_factor = 1.4814814815`. This will clamp a range for our quantization operation.

Finally we normalize each value in the original tensor by `scaling_factor` and rounding to the nearest whole number. This gives us the quantized vector:
```python
quantized_vec = [int(v * scaling_factor) for v in vec] # [1, 0, -3, 1, -2, 1, 2, 4]
```

To dequantize our values, we simply perform the inverse and should expect a loss in precision due to the information compression. 

(Source: https://huggingface.co/blog/hf-bitsandbytes-integration) 

Should I need to have a scaling factor inside of the MPS kernel? I.e. is it fine to assume that I am multiplying integers with eachother? I could imagine that two operands that are within the int4 range will go outside of it after multiplication.


Is the scaling factor assumed to be provided as an argument for the kernels i.e. this https://github.com/huggingface/quanto/blob/try-4bit-mm/quanto/library/ext/cpp/udqmm.cpp#L11.

#### Unpacking 

This relates more to matrix sizes and the order of packing and quantization. 

Lets say I am multiplying two tensors `A` and `B` of 8-bit precision with (dimensions AxB and BxC respectively). Is it fine to assume that we have two 4-bit quantized values in each entry of the tensors? In other words, unpacking the tensors result in a result matrix of size `2A x 2B`? Which then should get packed back into the 8-bit representation.
   
 #### Matrix Multiplication
 
 I should expect to perform MM only on 2D tensors representing matricies. Is there a certain kernel I should try to aim for here: https://siboehm.com/articles/22/CUDA-MMM ??
 
 Thank you so much again for the help 😊

**Comment by dacorvo** [comment]
> Also, I see that you developed https://github.com/huggingface/quanto/blob/main/quanto/library/ext/mps/unpack.mm#L8. Do you have any advice on tooling to assist with the debugging and profiling MPS kernels? I'm running VS Code and I generally use CLI tools, however I'm open to any of your suggestions.

This kernel was so simple I did not need to debug.
I would look at:
https://developer.apple.com/documentation/metal/
https://developer.apple.com/documentation/xcode/metal-debugger

**Comment by dacorvo** [comment]
> Oh I am now seeing a benchmark script. Thank you for having this! I've gone ahead used it, so I am noticing a ~3x speedup switching from the torch provided CPU to the MPS provided matrix operations.
> 
> ```
> udqmm_4bit[cpu]: python = 3.201 ms, ext = 3.166 ms, ratio = 1.0x
> udqmm_4bit[mps]: python = 1.185 ms, ext = 1.611 ms, ratio = 0.7x
> ```
> 
> Also, could you clarify the performance benchmarks for a PR that I should aim for? I'm going off an assumption that anything above a 3x speedup is a win, but I'm probably wrong.

You should not compare CPU vs Metal here: this simply indicates that `mm` is faster on MPS, which is expected.
What you should compare is the default implementation of `unpack` in python using only pytorch ops and your kernel.
Here, your kernel is 30% slower than the python version, which is not so good.

**Comment by dacorvo** [comment]
> Is the scaling factor assumed to be provided as an argument for the kernels i.e. this https://github.com/huggingface/quanto/blob/try-4bit-mm/quanto/library/ext/cpp/udqmm.cpp#L11.
> 
Yes
> #### Unpacking
> This relates more to matrix sizes and the order of packing and quantization.
> 
> Lets say I am multiplying two tensors `A` and `B` of 8-bit precision with (dimensions AxB and BxC respectively). Is it fine to assume that we have two 4-bit quantized values in each entry of the tensors? In other words, unpacking the tensors result in a result matrix of size `2A x 2B`? Which then should get packed back into the 8-bit representation.
>
No. Only the second term needs to be unpacked. The first is in float.
When packing you divide the packing dimension by two because you store two weights in one spot.
When unpacking you duplicate this tensor to get back two tensors of half the original size that are then concatenated back
to the original size.

> #### Matrix Multiplication
> I should expect to perform MM only on 2D tensors representing matricies. Is there a certain kernel I should try to aim for here: https://siboehm.com/articles/22/CUDA-MMM ??

I think this repo has interesting MPS kernels: https://github.com/ml-explore/mlx

**Comment by alejandroarmas** [comment]
Thank you @dacorvo for the patience!! I decided it would be more helpful if I wrote the "mps kernel" in python so that we can have alignment on what algorithm we'd like from https://github.com/ml-explore/mlx. 

This is still WIP as I have written a naive MM. The way I undestood the requirements was that we wanted to have the right tensor unpacked and then scaled. Afterwards, we'd have our matricies multiplied. 

What this naive MM does not do: it does not fuse the unpacking/scaling with the MM step. I will work on that right now.

Once I demonstrate it passes test cases then I would then rewrite it in MPS. How does that sound?

**Pull request closed without merging**
