### PR TITLE
enable cpu integer matmul

### PR DESCRIPTION
**Pull request by maktukmak**
Regarding issue [#64](https://github.com/huggingface/quanto/issues/64), torch now supports integer matmul (toch._int_mm) on the CPU at its master branch with this [PR](https://github.com/pytorch/pytorch/pull/121792) merged. Here, I made small changes to enable this kernel on quanto. To use the new backend, install torch nightly build after quanto.

### CODE REVIEW

**Comment by dacorvo** [comment]
Thank you for the pull-request ! I'd rather guard the call to int_mm to a minimum pytorch version to avoid errors with curren t pytorch.
Something like:

```python
from packaging import version

...
if version.parse(torch.__version__) < version.parse(2.3.0):
    # Use CPU int_mm
```

**Comment by maktukmak** [comment]
Got it. I added release version control so it can work with the current nightly build.

**Review by dacorvo — CHANGES_REQUESTED** [review]
Looks good to me, but you need to:
- fix style (`make style` from the root directory),
- rebase on main (no merge please: `git rebase <commit-before-your-branch> --onto upstream/main`).

**Comment by maktukmak** [comment]
@dacorvo, I rebased and did make style. Let me know if I missed something

**Comment by dacorvo** [comment]
Merged as #130

**Comment by dacorvo** [comment]
> @dacorvo, I rebased and did make style. Let me know if I missed something

I don't know how you applied styling, but it was all wrong ... I fixed your branch and vreated anoter pull-request.

**Pull request closed without merging**
